---
namespace: aap-24-dev
name_gateway: ""
name_controller: controller-dev
name_eda: ""
name_hub: hub-dev

automationcontroller:
  spec:
    admin_password_secret: "{{ name_controller }}-admin-password"
    route_host: controller-dev.example.com

  spec:
    admin_password_secret: "{{ name_hub }}-admin-password"
    route_host: hub-dev.example.com

secrets:
  - name: "{{ name_controller }}-admin-password"
    data:
      password: foobar

  - name: "{{ name_hub }}-admin-password"
    data:
      password: foobar2
