---
namespace: aap-24-dev
name_gateway: ""
name_controller: aap-24-dev
name_eda: ""
name_hub: ""

automationcontroller:
  spec:
    admin_password_secret: "{{ name_controller }}-admin-password"
    route_host: aap-24-dev.example.com

secrets:
  - name: "{{ name_controller }}-admin-password"
    data:
      password: foobar
