---
namespace: "aap"
name: "platform_on_ocp"
version: 1.0.0
description: >
  A collection containing roles that help to create, deploy, and manage k8s resources
  associated with a Red Hat Ansible Automation Platform Operator deployment.
readme: README.md
authors:
  - Homero Pawlowski @homeski
repository: https://github.com/homeski/ansible-collection-aap-platform-on-ocp
issues: https://github.com/homeski/ansible-collection-aap-platform-on-ocp/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
license_file: LICENSE
tags:
  - aap
  - cloud
  - openshift
  - operator
