apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: myaap-controller
  namespace: aap-25
spec:
  admin_password_secret: myaap-controller-admin-password
  admin_user: admin
  auto_upgrade: false
  create_preload_data: false
  garbage_collect_secrets: false
  image_pull_policy: IfNotPresent
  ingress_type: Route
  ipv6_disabled: false
  loadbalancer_ip: ''
  loadbalancer_port: 80
  loadbalancer_protocol: http
  metrics_utility_cronjob_gather_schedule: '@hourly'
  metrics_utility_cronjob_report_schedule: '@monthly'
  metrics_utility_enabled: false
  metrics_utility_pvc_claim_size: 5Gi
  no_log: true
  postgres_configuration_secret: myaap-controller-postgres-configuration
  postgres_keepalives: true
  postgres_keepalives_count: 5
  postgres_keepalives_idle: 5
  postgres_keepalives_interval: 5
  postgres_storage_class: lvms-vg1
  projects_persistence: false
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  replicas: 1
  route_tls_termination_mechanism: Edge
  secret_key_secret: myaap-controller-secret-key
  set_self_labels: true
  task_privileged: false
