apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canonical-controller-pvc-projects
  namespace: aap-canonical
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: lvms-vg1
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
