---
- name: Generate kubemanifests files
  hosts: all
  gather_facts: false
  tasks:
    - name: Import role
      ansible.builtin.import_role:
        name: aap.platform_on_ocp.generate_kubemanifests
      delegate_to: localhost
      when: namespace is defined
