---
- name: Manage kubemanifests
  hosts: all
  gather_facts: false
  tasks:
    - name: Import role
      ansible.builtin.import_role:
        name: aap.platform_on_ocp.manage_kubemanifests
      delegate_to: localhost
