---
operatorgroups:
  - metadata:
      name: ansible-automation-platform-operator
      namespace: aap
    spec:
      targetNamespaces: []

subscriptions:
  - metadata:
      name: ansible-automation-platform-operator
      namespace: aap
    spec:
      channel: stable-2.5-cluster-scoped
